# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscounInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('lkurl', models.CharField(max_length=500)),
                ('imgurl', models.CharField(max_length=500)),
            ],
        ),
    ]
