# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20180128_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountInfo',
        ),
    ]
