# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0014_discountinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountInfo',
        ),
    ]
