# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wechat', '0015_delete_discountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('lkurl', models.CharField(max_length=500)),
                ('imgurl', models.CharField(max_length=500)),
                ('merchant', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
